### ISSUE TITLE
Gas limit override feature

### ISSUE THREAD

**Issue by dec0dOS** [uniswap-integration/simple-uniswap-sdk#26]
Hello, thanks for the awesome project!
Simple-uniswap-sdk is really useful!

I have a problem with the automatic gas limit detection. It is often set for a too-small value, so I keep getting the ` Warning! Error encountered during contract execution [Out of gas]` on my trade transactions. Is there any way to manually set the Gas Limit?

**Comment by joshstevens19** [comment]
Hey the sdk only returns you the tx without any gas limit defined its up you to fill the gaps with it yourself. If you don’t and send it to web3 or ethers it will try to estimate it for you. 

We just return: 

transaction: {
    to: string;
    from: string;
    data: string;
    value: string;
  };

hope this helps!

**Comment by joshstevens19** [comment]
to set you can just set it on that transaction object aka transaction.gas = xxxx etc etc
