### ISSUE TITLE
not working on goerli test network?

### ISSUE THREAD

**Issue by ctrngk** [uniswap-integration/simple-uniswap-sdk#3]
const uniswapPair = new UniswapPair({
    fromTokenContractAddress: '0xf74a5ca65e4552cff0f13b116113ccb493c580c5',
    toTokenContractAddress: '0x2ac3c1d3e24b45c6c310534bc2dd84b5ed576335',
chainId: ChainId.GÖRLI,
...
})
which returns 
```
UniswapError: invalid from or to contract tokens
```

Those goerli tokens are from https://explorer.bitquery.io/goerli/tokens which should be valid

**Comment by joshstevens19** [comment]
Hey thanks for raising it, I have now made this support `goerli` just so you know your query will now return 

```
 UnhandledPromiseRejectionWarning: UniswapError: No routes found for 0xf74a5ca65E4552CfF0f13b116113cCb493c580C5 > 0x2aC3c1d3e24b45c6C310534Bc2Dd84B5ed576335
 ``` < but that's a normal error from the lib it can not found any route paths to take you so make sure the tokens you are querying all have pools to weth! 
 
 simple-uniswap-sdk@2.2.0 holds the fix
